### ISSUE TITLE
Ordering of Indices files

### ISSUE THREAD

**Issue by jaseeverett** [jaseeverett/IMOS_Toolbox#4]
@clairedavies A minor issue but it would be useful if, when creating the Indices file, you could arrange the columns so that the satellite data goes adjacent to the chemical data. So it makes it easy to keep/remove all the enviro data as required. Putting the enviro data at the end probably makes more sense?

Therefore we can use tidyverse syntax to easily extract what you need. For example to extract only the phyto data it would great to do:
```
data <- data %>% select(c(NRScode::DinoflagellateEvenness)
```

**Comment by clairedavies** [comment]
ok, order is zooplankton, phytoplankton, CTD, satellite, nuts

**Comment by jaseeverett** [comment]
Great. Thanks @clairedavies
